config/routes.rb
ChiSquared::Application.routes.draw do
  resources :trackings

end

app/models/tracking.rb
class Tracking < ActiveRecord::Base
  attr_accessible :filetype, :ftpcomplete, :ftpqueue, :ftpstart, :importcomplete, :importqueue, :importstart, :notes, :sourcefile
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/trackings_controller.rb
class TrackingsController < ApplicationController
  # GET /trackings
  # GET /trackings.json
  def index
    @trackings = Tracking.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @trackings }
    end
  end

  # GET /trackings/1
  # GET /trackings/1.json
  def show
    @tracking = Tracking.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tracking }
    end
  end

  # GET /trackings/new
  # GET /trackings/new.json
  def new
    @tracking = Tracking.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tracking }
    end
  end

  # GET /trackings/1/edit
  def edit
    @tracking = Tracking.find(params[:id])
  end

  # POST /trackings
  # POST /trackings.json
  def create
    @tracking = Tracking.new(params[:tracking])
    
    @tracking.ftpqueue = nil
    @tracking.ftpstart = nil
    @tracking.ftpcomplete = nil
    @tracking.importqueue = Time.now
    @tracking.importstart = nil
    @tracking.importcomplete = nil

    respond_to do |format|
      if @tracking.save
        `at -f \"#{Rails.root}/app/scripts/launcher.sh\" -M now + 2 minutes`
        
        format.html { redirect_to @tracking, notice: 'Tracking was successfully created.' }
        format.json { render json: @tracking, status: :created, location: @tracking }
      else
        format.html { render action: "new" }
        format.json { render json: @tracking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /trackings/1
  # PUT /trackings/1.json
  def update
    @tracking = Tracking.find(params[:id])

    respond_to do |format|
      if @tracking.update_attributes(params[:tracking])
        format.html { redirect_to @tracking, notice: 'Tracking was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tracking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trackings/1
  # DELETE /trackings/1.json
  def destroy
    @tracking = Tracking.find(params[:id])
    @tracking.destroy

    respond_to do |format|
      format.html { redirect_to trackings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trackings_helper.rb
module TrackingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chi Squared :: Analytics Manager</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<div class="navbar navbar-fixed-top">
 	<div class="navbar-inner">
  	<div class="container">
			<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

    	<a class="brand" href="#">&Chi;<sup>2</sup></a>

			<div class="nav-collapse">
				<ul class="nav">
				  <li><a href="/">Home</a></li>
				  <li><a href="#">Rank Sheets</a></li>
				  <li class="dropdown">
				  	<a href="#" class="dropdown-toggle" data-toggle="dropdown">Reports
				  		<b class="caret"></b>
				  	</a>
				  	<ul class="dropdown-menu">
				  		<li><a href="#">Territory Summary</a></li>
				  		<li><a href="#">Budget Calculator</a></li>
			  		</ul>
				  </li>
				</ul>
			</div>
		</div>
	</div>
</div>

<div class ="container">
	<div class="row">
		<div class="span9"><%= yield %>
</div>
		<div class="span3">
			<h2>Directions</h2>
			<ol>
			<li>Et craft beer direct trade freegan, before they sold ou</li>
			<li>Selvage pork belly brunch anim, williamsburg tattooed wolf elit aliquip.</li>
			<li>Reprehenderit in sint, truffaut pariatur tempor echo park ea adipisicing elit single-origin coffee nihil 8-bit gastropub vegan.</li>
			<li>Artisan small batch narwhal, aute PBR brunch pickled keytar.</li>
			<li>Placeat locavore small batch est freegan.</li>
			<li>Farm-to-table PBR etsy vinyl you probably haven't heard of them four loko.</li>
		</div>
		</div>
</div>

</body>
</html>

app/views/trackings/_form.html.erb
<%= form_for(@tracking) do |f| %>
  <% if @tracking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tracking.errors.count, "error") %> prohibited this tracking from being saved:</h2>

      <ul>
      <% @tracking.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :sourcefile %><br />
    <%= f.text_field :sourcefile %>
  </div>
  <div class="field">
    <%= f.label :filetype %><br />
    <%= select(:tracking, :filetype, [['address info','address info'],['geography data','geography data'],['sales info','sales info']]) %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_area :notes, :rows=>4 %>
  </div>
  <div style="visibility: hidden; display: none;">
	  <div class="field">
	    <%= f.label :ftpqueue %><br />
	    <%= f.datetime_select :ftpqueue %>
	  </div>
	  <div class="field">
	    <%= f.label :ftpstart %><br />
	    <%= f.datetime_select :ftpstart %>
	  </div>
	  <div class="field">
	    <%= f.label :ftpcomplete %><br />
	    <%= f.datetime_select :ftpcomplete %>
	  </div>
	  <div class="field">
	    <%= f.label :importqueue %><br />
	    <%= f.datetime_select :importqueue %>
	  </div>
	  <div class="field">
	    <%= f.label :importstart %><br />
	    <%= f.datetime_select :importstart %>
	  </div>
	  <div class="field">
	    <%= f.label :importcomplete %><br />
	    <%= f.datetime_select :importcomplete %>
	  </div>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trackings/edit.html.erb
<h1>Editing tracking</h1>

<%= render 'form' %>

<%= link_to 'Show', @tracking %> |
<%= link_to 'Back', trackings_path %>

app/views/trackings/index.html.erb
<h1>Listing trackings</h1>

<%= link_to 'New Tracking', new_tracking_path %>
<table>
  <tr>
  	<th colspan="2">&nbsp;</th>
  	<th colspan="3" class="import">Import</th>
  	<th>&nbsp;</th>
  </tr>
  <tr>
    <th class="file">File</th>
    <th class="type">Type</th>
    <th class="time">[queue]</th>
    <th class="time">[start]</th>
    <th class="time">[complete]</th>
    <th class="notes">Notes</th>
  </tr>

<% @trackings.each do |tracking| %>
  <tr class="<%= cycle("data", "datab") %>">
    <td><%= tracking.sourcefile %></td>
    <td><%= tracking.filetype %></td>
    <td><%= tracking.importqueue.in_time_zone("Eastern Time (US & Canada)").strftime '%m-%d-%Y %H:%M:%S' %></td>
    <td><%= tracking.importstart.try(:in_time_zone, "Eastern Time (US & Canada)").try(:strftime, '%m-%d-%Y %H:%M:%S') %></td>
    <td><%= tracking.importcomplete.try(:in_time_zone, "Eastern Time (US & Canada)").try(:strftime, '%m-%d-%Y %H:%M:%S') %></td>
    <td><%= tracking.notes %></td>
  </tr>
<% end %>
</table>

<br />

app/views/trackings/new.html.erb
<h1>New tracking</h1>

<%= render 'form' %>

<%= link_to 'Back', trackings_path %>

app/views/trackings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Sourcefile:</b>
  <%= @tracking.sourcefile %>
</p>

<p>
  <b>Filetype:</b>
  <%= @tracking.filetype %>
</p>

<p>
  <b>Notes:</b>
  <%= @tracking.notes %>
</p>

<p>
  <b>Ftpqueue:</b>
  <%= @tracking.ftpqueue %>
</p>

<p>
  <b>Ftpstart:</b>
  <%= @tracking.ftpstart %>
</p>

<p>
  <b>Ftpcomplete:</b>
  <%= @tracking.ftpcomplete %>
</p>

<p>
  <b>Importqueue:</b>
  <%= @tracking.importqueue %>
</p>

<p>
  <b>Importstart:</b>
  <%= @tracking.importstart %>
</p>

<p>
  <b>Importcomplete:</b>
  <%= @tracking.importcomplete %>
</p>


<%= link_to 'Edit', edit_tracking_path(@tracking) %> |
<%= link_to 'Back', trackings_path %>